li = list()
print(li)
li.append(100)
li.append(50)
li.append(60)
print(li)
li.insert(2,200)
print(li)
li.extend([33,44,55])
print(li)
print("Delete element is : ",li.pop())
print(li)
print("Deleted element is : ",li.pop(1))
print(li)
li.remove(200)
print(li)
li.clear()
print(li)